### ISSUE TITLE
Completion not working?

### ISSUE THREAD

**Issue by spacekookie** [ibensw/CComplete#2]
Hey, I just installed your plugin and it's not giving me sugestions while typing. I tried to find a hotkey that should be triggered but came up short.

Is this a problem with my setup, your plugin or OSI8? :)

Arch Linux 4.6.3, awesomewm
Sublime Text - Dev Channel 3118
CComplete v0.1.1

Hope you can help me. Thanks :)

**Comment by ibensw** [comment]
Hi spacecookie,

The default shortcut for code completion suggestions in sublime is ctrl+space. But it can be modified in the settings.
You can have the completions automatically popup on typing . or -> with these lines in your user settings file:
    "auto_complete_triggers":
    [
        {
            "characters": ".>",
            "selector": "source.c"
        }
    ],
Also, make sure "auto_complete" is not disabled in your settings.

If that doesn't fix it, you can open the console (ctrl+~) and scan the output for errors. You can post the output here and I will have a look at it.

Kind regards,
Wouter
